### ISSUE TITLE
conversion does not seem to be working

### ISSUE THREAD

**Issue by bcojan** [jakubknejzlik/cgbi-to-png#1]
Hello, 
I'm trying to use your package as I would like to use png files that are contained into an IPA on a website. 

I can't seem to see the image generated by cgbiToPng method in my browser. 

I'm happy to provide more information if needed

**Comment by jakubknejzlik** [comment]
Hi, it would be great, if you provide more info. Especially:
- do you provide correct path to app icon?
- does the script outputs any messages/errors?
- "can't see the image" means browser is not correctly displaying it?

**Comment by bcojan** [comment]
Hello Jakub,

This is what I'm trying to do:

```
var cgbiToPng = require('cgbi-to-png');
var input=fs.createReadStream("icon.png");
var output = fs.createWriteStream('icon.new.png');

cgbiToPng(input,function(err,pngStream){
  pngStream.pipe(output);
});
```

I have attached the images. I don't get an error from the cgbiToPng function
Is there anything I'm doing wrong?

Alternatively, I've been looking at
https://www.npmjs.com/package/node-pngdefry, but I prefer your project as
we can work on streams directly.

Best,
Bastien

**Comment by jakubknejzlik** [comment]
this looks ok. Maybe it's about the concrete png(cgbi) file. Does the buffer version produce similar result? Also is it the problem with any of your files or only one of them?

**Comment by bcojan** [comment]
I have the same result with the buffer version

```
var cgbiBuffer = fs.readFileSync("cgbi-image.png");
var pngBuffer = cgbiToPng.revert(cgbiBuffer);
fs.writeFileSync("cgbi-image.new.png",pngBuffer);
```

I don't think it's the image as I have also tried with the one provided in
your test directory

**Comment by jakubknejzlik** [comment]
That's strange. But if you have problem even with image from tests, it's probably something outside of script (maybe nodejs version, way you're displaying image etc.)

**Comment by bcojan** [comment]
I'm running node v5.4.1 on mac OS X 10.11.3. and trying to open the image with Chrome (v49). I'm not using Safari as I suspect you can open cgbi images with safari

**Comment by jakubknejzlik** [comment]
@bcojan could you please check the latest fix (more info #2) ... I guess it could be the same source of problems

**Comment by tspoke** [comment]
I had the same problem. I updated the module to the last version referred in #2 and everything is working fine now.
Thank's !

**Comment by jakubknejzlik** [comment]
Great, thanks for feedback!
