### ISSUE TITLE
It does nothing to the png file

### ISSUE THREAD

**Issue by teebu** [jakubknejzlik/cgbi-to-png#2]
Running test, gives back the same identical file.

node v4.4.2

![cgbi-image](https://cloud.githubusercontent.com/assets/5531844/18726552/d7e333e6-7ff9-11e6-8c29-70cb18662b29.png)
![tmp-24168nmjprepoi6r0](https://cloud.githubusercontent.com/assets/5531844/18726553/d7e5438e-7ff9-11e6-8228-56447870a2d3.png)

**Comment by jakubknejzlik** [comment]
Hi @teebu, could you please update links to files (or send them via mail)? Current links doesn't seem to work.

**Comment by teebu** [comment]
that is just the same file in the test folder.

i zipped them both up: https://www.dropbox.com/s/uj9hfq8o0m6hu2m/test.zip?dl=0

My own test image if you want that too: https://www.dropbox.com/s/yuy1amktc2smc8f/COIN.png?dl=0

my test image tested with this python code and it works: https://gist.github.com/urielka/3609051 but I was looking for a nodejs alternative.

**Comment by jakubknejzlik** [comment]
Thanks, I'll check it

**Comment by teebu** [comment]
I noticed ont this line, https://github.com/jakubknejzlik/cgbi-to-png/blob/master/index.js#L59 it's trying to compare a non existant variable. So, this probably should be `if chunk.type is 'IDAT'` 

But even with that, I wasnt getting the right results. After looking at the HEX of the output file, I can still see that CgBI is still in the png. That means, the script is not removing that, which it should. 

I was also trying to figure out why the inflateRawSync option of `windowBits: -15` is an error. But python was ok with that.

**Comment by jakubknejzlik** [comment]
You are correct. I'm investigating the problem, but got stuck with the inflate/deflate stuff

**Comment by jakubknejzlik** [comment]
@teebu I've updated the master, looks ok at my side. Could you check it please?

**Comment by jakubknejzlik** [comment]
The only thing left is CRC which is currently not generated correctly according to pngcheck (but I didn't have any issues viewing it so far)

**Comment by teebu** [comment]
ill check, but first glance

```
 console.log(chunkCRC, '....');
        idat_chunk = {
          'type': 'IDAT',
          'length': idatData.length,
          'data': idatData,
          'crc': 123
        };
```

123?

**Comment by jakubknejzlik** [comment]
Damn! Sorry for that, late working took it's price...fixed

**Comment by teebu** [comment]
Haha, looks like its working. Now, to figure out what you did to fix it :)

**Comment by teebu** [comment]
So far so Good @jakubknejzlik thanks, ill run a few more test files through it. I assume it handles multiple IDATS and ignores apngs?

**Comment by jakubknejzlik** [comment]
Glad to hear it :) ... basically fixed the undefined `x` to `chunk.type` (thanks), removed iDOT/CgBI chunks, switched IDAT from string to buffer (maybe not necessary, but IMO should be better than appending string) and used `zlib.deflat` instead of `deflateRaw`

**Comment by jakubknejzlik** [comment]
currently it joins IDATs to one chunk and convert it to PNGs format...I'm thinking leaving IDATs separated, but I'm not sure if it won't break anything.

**Comment by jakubknejzlik** [comment]
Thanks for feedback, if you didn't find any glitches I assume it's ready for version update.

**Comment by teebu** [comment]
No glitches so far. Looks good.

**Comment by teebu** [comment]
There is a slight issue when trying to work on non-cgbi png's. It should just return the buffer, instead of whatever it does.

**Comment by jakubknejzlik** [comment]
I've added fix and tests for non cgbi cases. Should be fine now.

**Comment by teebu** [comment]
k ill run some more tests

**Comment by teebu** [comment]
I dumped 200 pngs (compressed and not), apngs, gifs, and misc, and it ran through them super fast. Way faster then the python version.

**Comment by jakubknejzlik** [comment]
🎉

**Comment by teebu** [comment]
closing
